apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: mwrobel02/bp-api:1.0
        ports:
        - containerPort: 3001
        env:
        - name: SECRET_VALUE
          value: "myValue"
        - name: CLIENT_SECRET_VALUE
          value: "myOtherValue"
---
apiVersion: v1
kind: Service
metadata:
  name: express-api-service
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
