# k8s.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-client-deployment
  labels:
    app: bp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-client
  template:
    metadata:
      labels:
        app: bp-client
    spec:
      containers:
      - name: bp-client
        image: mwrobel02/bp_client:1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bp-client-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: bp-client
